databases:
  - name: kowope
    databaseName: budget-app
    user: toyman

services:
  - type: web
    name: kowope
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kowope
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false