databases:
  - name: kowope
    databaseName: kkowope_app
    user: kowope_app_user

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kowope_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false